[package]
name = "ai_provider"
version = "0.1.0"
edition = "2021"
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
http.workspace = true
http_client.workspace = true
hyper.workspace = true
prost.workspace = true
warp_core.workspace = true
reqwest.workspace = true
reqwest-eventsource.workspace = true
serde_json.workspace = true
thiserror.workspace = true
warp_multi_agent_api.workspace = true
